welinkeo_back_office:
    resource: "@WelinkeoBackOfficeBundle/Resources/config/routing.yml"
    prefix:   /back

welinkeo_catalogue:
    resource: "@WelinkeoCatalogueBundle/Resources/config/routing.yml"
    prefix:   /catologue

welinkeo_commande:
    resource: "@WelinkeoCommandeBundle/Resources/config/routing.yml"
    prefix:   /commande

welinkeo_panier:
    resource: "@WelinkeoPanierBundle/Resources/config/routing.yml"
    prefix:   /panier

welinkeo_utilisateur:
    resource: "@WelinkeoUtilisateurBundle/Resources/config/routing.yml"
    prefix:   /utilisateur

welinkeo_general:
    resource: "@WelinkeoGeneralBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
