<?php

namespace Welinkeo\PanierBundle\Repository;

/**
 * LignecommandeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LignecommandeRepository extends \Doctrine\ORM\EntityRepository
{
}
