<?php

namespace Welinkeo\PanierBundle\Repository;

/**
 * PointlivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointlivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
