<?php

namespace Welinkeo\CatalogueBundle\Repository;

/**
 * CommandestatutRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommandestatutRepository extends \Doctrine\ORM\EntityRepository
{
}
