<?php

namespace Welinkeo\CommandeBundle\Repository;

/**
 * ImagemodelRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagemodelRepository extends \Doctrine\ORM\EntityRepository
{
}
