<?php

namespace Welinkeo\UtilisateurBundle\Repository;

/**
 * ImagecategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagecategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
