<?php

namespace Welinkeo\UtilisateurBundle\Repository;

/**
 * ImagesouscategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImagesouscategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
