<?php

namespace Welinkeo\BackOfficeBundle\Repository;

/**
 * ModepaiementRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModepaiementRepository extends \Doctrine\ORM\EntityRepository
{
}
