<?php

namespace Welinkeo\BackOfficeBundle\Repository;

/**
 * ModelivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModelivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
