<?php

namespace Welinkeo\BackOfficeBundle\Repository;

/**
 * TypepointlivraisonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TypepointlivraisonRepository extends \Doctrine\ORM\EntityRepository
{
}
